export const LOADING = "LOADING";
export const ACCOUNTINFO="ACCOUNTINFO";
export const ACCOUNTINFO_ERROR="ACCOUNTINFO_ERROR";
export const EMPTY_ERROR_COMMON_OBJ="EMPTY_ERROR_COMMON_OBJ";
export const SUBSCRIPTIONACCOUNTINFO='SUBSCRIPTIONACCOUNTINFO';
export const SUBSCRIPTIONACCOUNTINFO_ERROR='SUBSCRIPTIONACCOUNTINFO_ERROR';
export const UPDATEACCOUNTINFO="UPDATEACCOUNTINFO";
export const UPDATEACCOUNTINFO_ERROR="UPDATEACCOUNTINFO_ERROR";