export const COMPANY_DETAILS = 'COMPANY_DETAILS'
export const EMPLOYEE_LIST = 'EMPLOYEE_LIST'
export const DEPARTMENT_LIST = 'DEPARTMENT_LIST'
export const SUBMIT_EXECUTIVE_LEAD = 'SUBMIT_EXECUTIVE_LEAD'