export const CLOSED_OPPORTUNITY = "CLOSED_OPPORTUNITY";
export const CLOSED_OPPORTUNITY_ERROR="CLOSED_OPPORTUNITY_ERROR";
export const OPEN_OPPORTUNITY="OPEN_OPPORTUNITY";
export const OPEN_OPPORTUNITY_ERROR="OPEN_OPPORTUNITY_ERROR";
export const DASHBOARD_GROUPED_COUNT="DASHBOARD_GROUPED_COUNT";
export const DASHBOARD_GROUPED_COUNT_ERROR="DASHBOARD_GROUPED_COUNT_ERROR";
export const DASHBOARD_SALES_TREND="DASHBOARD_SALES_TREND";
export const DASHBOARD_SALES_TREND_ERROR="DASHBOARD_SALES_TREND_ERROR";