export const CLOSED_OPPORTUNITY = "CLOSED_OPPORTUNITY";
export const CLOSED_OPPORTUNITY_ERROR="CLOSED_OPPORTUNITY_ERROR";
export const OPEN_OPPORTUNITY="OPEN_OPPORTUNITY";
export const OPEN_OPPORTUNITY_ERROR="OPEN_OPPORTUNITY_ERROR";