export const LEAD_DETAILS = 'LEAD_DETAILS'
export const LEAD_EMPTY_ERROR_OBJ='LEAD_EMPTY_ERROR_OBJ'  
export const LEAD_DETAILS_ERROR = 'LEAD_DETAILS_ERROR';
export const UPDATE_LEAD_DETAILS = 'UPDATE_LEAD_DETAILS';
export const UPDATE_LEAD_DETAILS_ERROR = 'UPDATE_LEAD_DETAILS_ERROR';
