export const LEAD_DETAILS = 'LEAD_DETAILS'
export const SAVE_CLIENT_NOTE='SAVE_CLIENT_NOTE';
export const LEAD_EMPTY_ERROR_OBJ='LEAD_EMPTY_ERROR_OBJ'  
export const LEAD_DETAILS_ERROR = 'LEAD_DETAILS_ERROR';
export const UPDATE_LEAD_DETAILS = 'UPDATE_LEAD_DETAILS';
export const UPDATE_LEAD_DETAILS_ERROR = 'UPDATE_LEAD_DETAILS_ERROR';
export const SAVE_CLIENT_NOTE_ERROR='SAVE_CLIENT_NOTE_ERROR';

export const LEAD_NOTES = 'LEAD_NOTES'
export const LEAD_NOTES_ERROR = 'LEAD_NOTES_ERROR';
export const LEAD_REMARKS = 'LEAD_REMARKS'
export const LEAD_REMARKS_ERROR = 'LEAD_REMARKS_ERROR';
export const LEAD_NOTE_DETAIL = 'LEAD_NOTE_DETAIL'
export const LEAD_NOTE_DETAIL_ERROR = 'LEAD_NOTE_DETAIL_ERROR';
