export const signInUrl = "api/authenticate"; //"signin.php";
export const signUpUrl = "api/register";
export const industryApiUrl = "api/industries";
export const employeeCountApiUrl = "api/employee-ranges";
export const companyTypeApiUrl = "api/companycategories";
export const revenueRangeApiUrl = "api/company-revenue-ranges";
export const companyListingApiUrl = "api/companies";
export const companyExlDownloadUrl = "api/companies/exl";
export const companyPdfDownloadUrl = "api/companies/pdf";
export const employeeListUrl = "api/employees";
export const executiveDepartmentList = "api/executive-functions";
export const clientLeadsUrl = "/api/client-leads";
export const errorReport = "/api/incorrect-data-reporteds";
export const saveSearch = '/api/externaldatadumps'
