export const Geolocation = [
  {
    India: [
      { "Andaman & Nicobar": ["South Andaman"] },
      {
        "Andhra Pradesh": [
          "Anantapuramu",
          "Chittoor",
          "East Godavari",
          "Gachibowli, Hyderabad",
          "Guntur",
          "Hyderabad",
          "Krishna",
          "Kurnool",
          "Mahbubnagar",
          "Medchal–Malkajgiri",
          "Prakasam",
          "Ranga Reddy",
          "Sangareddy",
          "Sri Potti Sriramulu Nellore",
          "Srikakulam",
          "Tadepalligudem",
          "Visakhapatnam",
          "West Godavari",
          "YSR Kadapa",
        ],
      },
      { "Arunachal Pradesh": ["Papum pare", "Itanagar"] },
      {
        Assam: [
          "Cachar",
          "Dibrugarh",
          "Jorhat",
          "Kamrup Metropolitan",
          "Sonitpur",
        ],
      },
      {
        Bihar: [
          "Begusarai",
          "Bhagalpur",
          "Chandigarh",
          "East Champaran",
          "Gaya",
          "Katihar",
          "Muzaffarnagar",
          "Nalanda",
          "Patna",
          "Purnea",
          "Rohtas",
          "Samastipur",
          "Vaishali",
        ],
      },
      {
        Chandigarh: ["Chandigarh", "Mohali", "Panchkula", "Zirakpur"],
      },
      {
        Chhattisgarh: [
          "Bilaspur",
          "Durg",
          "Korba",
          "Raigarh",
          "Raipur",
          "Rajnandgaon",
        ],
      },
      { "Dadra and Nagar Haveli": ["Silvassa"] },
      { "Daman & Diu": ["Diu"] },
      { Delhi: ["Delhi"] },
      { Goa: ["North Goa", "Panaji", "South Goa"] },
      {
        Gujarat: [
          "Adalaj",
          "Ahmedabad",
          "Amreli",
          "Anand",
          "Ankleshwar",
          "Aravalli",
          "Banaskantha",
          "Bharuch",
          "Bhavnagar",
          "Bhilad",
          "Chhatral",
          "Devbhoomi Dwarka",
          "Gandhinagar",
          "Jamnagar",
          "Junagadh",
          "Kheda",
          "Kutch",
          "Mehsana",
          "Morbi",
          "Navsari",
          "Panchmahal",
          "Patan",
          "Porbandar",
          "Rajkot",
          "Sabarkantha",
          "Surat",
          "Surendranagar",
          "Vadodara/Baroda",
          "Valsad",
          "Vijapur",
          "Vitthal Udhyognagar",
        ],
      },
      {
        Haryana: [
          "Ambala",
          "Bahadurgarh",
          "Bhiwani",
          "Chandigarh",
          "Faridabad",
          "Gurgaon",
          "Gurugram",
          "Hisar",
          "Jhajjar",
          "Jind",
          "Kaithal",
          "Karnal",
          "Kurukshetra",
          "Mahendragarh",
          "Manesar",
          "Mewat",
          "Palwal",
          "Panchkula",
          "Panipat",
          "Rewari",
          "Rohtak",
          "Sirsa",
          "Sonipat",
          "Yamunanagar",
        ],
      },
      {
        "Himachal Pradesh": [
          "Hamirpur",
          "Kangra",
          "Kullu",
          "Manali",
          "Mandi",
          "Shimla",
          "Sirmaur",
          "Solan",
          "Una",
          "Lahaul And Spiti",
        ],
      },
      { "Jammu & Kashmir": ["Jammu", "Srinagar"] },
      {
        Jharkhand: [
          "Bokaro",
          "Deoghar",
          "Dhanbad",
          "East Singhbhum",
          "Giridih",
          "Jamshedpur",
          "Ranchi",
          "Seraikela Kharsawan",
          "Singhbhum",
          "Palamu",
        ],
      },
      {
        Karnataka: [
          "Bagalkot",
          "Bengaluru",
          "Bidar",
          "Bijapur",
          "Chikkaballapur",
          "Chikkamagaluru",
          "Dakshina Kannada",
          "Davanagere",
          "Dharwad",
          "Hassan",
          "Kalaburagi",
          "Kodagu",
          "Kolar",
          "Koppala",
          "Mandya",
          "Mangalore",
          "Mysuru",
          "New Udupi",
          "Raichur",
          "Ramanagara",
          "Shimoga",
          "Tumkur",
          "Udupi",
          "Uttara Kannada",
          "Vijayanagara",
        ],
      },
      {
        Kerala: [
          "Alappuzha",
          "Calicut",
          "Cochin",
          "Ernakulam",
          "Idukki",
          "JUBAIl",
          "Kakkanad Kochi",
          "Kannur",
          "Kasaragod",
          "Kochi",
          "Kollam",
          "Kottayam",
          "Kozhikode",
          "Kuala Lumpur",
          "Malappuram",
          "Palakkad",
          "Palghat",
          "Pathanamthitta",
          "Thiruvananthapuram",
          "Thrissur",
          "Tiruvalla",
          "Vadakara",
          "Wayanad",
        ],
      },
      { Ladkah: ["Leh"] },
      {
        "Madhya Pradesh": [
          "Balaghat",
          "Betul",
          "Bhopal",
          "Burhanpur",
          "Chhatarpur",
          "Chhindwara",
          "Dewas",
          "Dhar",
          "Gwalior",
          "Hoshangabad",
          "Indore",
          "Jabalpur",
          "Katni",
          "Khargone",
          "Mandla",
          "Mandsaur",
          "Morena",
          "Raisen",
          "Rajgarh",
          "Ratlam",
          "Rewa",
          "Sagar",
          "Satna",
          "Tikamgarh",
          "Ujjain",
        ],
      },
      {
        Maharashtra: [
          "Mumbai",
          "Ahmednagar",
          "Akola",
          "Amravati",
          "Aurangabad",
          "Buldhana",
          "Dhule",
          "Dombivli East",
          "Jalgaon",
          "Jalna",
          "Kolhapur",
          "Latur",
          "Lonavala",
          "Nagaur",
          "Nagpur",
          "Nanded",
          "Nasik",
          "Navi Mumbai",
          "Osmanabad",
          "Palghar",
          "Pune",
          "Raigad",
          "Ratnagiri",
          "Sangli",
          "Satara",
          "Shahapur",
          "Solapur",
          "Valsad",
          "Virar",
        ],
      },
      {
        Manipur: ["Imphal West", "Imphal East", "Churachandpur", "Ukhrul"],
      },
      { Meghalaya: ["Shillong", "CherraPunji"] },
      { Mizoram: ["Aizwal"] },
      { Nagaland: ["Dimapur", "Kohima"] },
      {
        Odisha: [
          "Baleswar",
          "Bhubaneshwar",
          "Rourkela",
          "Cuttack",
          "Dhenkanal",
          "Ganjam",
          "Jagatsinghpur",
          "Jharsuguda",
          "Kendujhar",
          "Khordha",
          "Koraput",
          "Puri",
          "Rayagada",
          "Sambalpur",
          "Sundargarh",
        ],
      },
      { Puducherry: ["Pondicherry"] },
      {
        Punjab: [
          "Amritsar",
          "Bahawalpur",
          "Bathinda",
          "Chandigarh",
          "Faridkot",
          "Fatehgarh Sahib",
          "Gurdaspur",
          "Hoshiarpur",
          "Jalandhar",
          "Kapurthala",
          "Kasur",
          "Lahore",
          "Ludhiana",
          "Mohali",
          "Pathankot",
          "Patiala",
          "Rupnagar",
          "Sangrur",
          "Sri Muktsar Sahib",
        ],
      },
      {
        Rajasthan: [
          "Ajmer",
          "Alwar",
          "Banswara",
          "Barmer",
          "Bharatpur",
          "Bhilwara",
          "Bhiwadi",
          "Bikaner",
          "Chittorgarh",
          "Jaipur",
          "Jaisalmer",
          "Jhalawar",
          "Jhunjhunu",
          "Jodhpur",
          "Kota",
          "Nagaur",
          "Pali",
          "Rajsamand",
          "Sawai Madhopur",
          "Sikar",
          "Sirohi",
          "Sri Ganganagar",
          "Udaipur",
        ],
      },
      { Sikkim: ["Gangtok"] },
      {
        "Tamil Nadu": [
          "Ariyalur",
          "Chattanooga",
          "Chengalpattu",
          "Chennai",
          "Coimbatore",
          "Cuddalore",
          "Dindigul",
          "Erode",
          "Hosur",
          "Kanchipuram",
          "Kanyakumari",
          "Karur",
          "Krishnagiri",
          "Madurai",
          "Mayiladuthurai",
          "Nagapattinam",
          "Namakkal",
          "Nilgiris",
          "Pudukkottai",
          "Ranipet",
          "Salem",
          "Thanjavur",
          "Thiruvallur",
          "Thoothukudi",
          "Tiruchirappalli",
          "Tirunelveli",
          "Tirupathur",
          "Tiruppur",
          "Tiruvallur",
          "Tiruvannamalai",
          "Vellore",
          "Viluppuram",
          "Virudhunagar",
        ],
      },
      {
        Telangana: [
          "Adilabad",
          "Bhadradri Kothagudem",
          "Hyderabad",
          "Janjgir–Champa",
          "Karimnagar",
          "Khammam",
          "Medak",
          "Medchal–Malkajgiri",
          "Nalgonda",
          "Nizamabad",
          "Peddapalli",
          "Ranga Reddy",
          "Sangareddy",
          "Warangal",
        ],
      },
      { Tripura: ["Agartala"] },
      {
        "Uttar Pradesh": [
          "Agra",
          "Aligarh",
          "Amroha",
          "Ayodhya",
          "Azamgarh",
          "Baghpat",
          "Barabanki",
          "Bareilly",
          "Bhadohi",
          "Bijnor",
          "Budaun",
          "Bulandshahr",
          "Etah",
          "Faridabad",
          "Firozabad",
          "Gautam Budh Nagar",
          "Ghaziabad",
          "Gorakhpur",
          "Greater Noida",
          "Hapur",
          "Jhansi",
          "Kanpur",
          "Kanpur Nagar",
          "Lucknow",
          "Mathura",
          "Meerut",
          "Mirzapur",
          "Moradabad",
          "Muzaffarnagar",
          "Noida",
          "Pilibhit",
          "Prayagraj",
          "Raebareli",
          "Rampur",
          "Saharanpur",
          "Sahibabad",
          "Shahjahanpur",
          "Sitapur",
          "Varanasi",
        ],
      },
      {
        Uttarakhand: [
          "Almora",
          "Dehradun",
          "Haridwar",
          "Nainital",
          "Pauri Garhwal",
          "Rudra Prayag",
          "Tehri Garhwal",
          "Mussorie",
          "Udham Singh Nagar",
        ],
      },
      {
        "West Bengal": [
          "Bankura",
          "Birbhum",
          "Darjeeling",
          "Hooghly",
          "Howrah",
          "Jalpaiguri",
          "Kolkata",
          "Kozhikode",
          "Nadia",
          "North 24 Parganas",
          "Purba Bardhaman",
          "Purba Medinipur",
          "Uttar Dinajpur",
          "West Medinipur",
        ],
      },
    ],
  }
  
];
