export const companyList = [
  {
    id: 11,
    name: "Amdocs",
    address: "B6/7 gurgaon",
    companyLogoUrl: "https://logo.clearbit.com/amdocs.com",
    pincode: "201308",
    phoneNo: "112312323",
    extn: "12",
    city: null,
    state: null,
    totalEmployees: 12344,
    companyRevenue: "565600",
    country: "india",
    geographyName: null,
    wedsite: "www.amdocs.com",
    symbol: "fds",
    listingName: "NSA",
    introduction:
      "Amdocs Development Centre India Private Limited acts as a subsidiary of Amdocs Inc., USA. The company is engaged into the business of IT Industry. Some of its products which include Customer Management, Revenue Management, Digital Services, Network Control, Operations Support Systems (OSS), etc. It has offices across the globe.",
    shortIntro: 'Amdocs Development Centre India Private Limited acts as a subsidiary of Amdocs Inc., USA. The company is engaged into the business of IT Industry. Some of its products which include Customer Management, Revenue Management, Digital Services, Network Control, Operations Support Systems (OSS), etc. It has offices across the globe.',
    socialLinks: [],
    industry: { id: 11, name: "Banking", description: null },
    range: null,
    revenue: { id: 17, name: "1001 and 5000", description: null },
    category: null,
  },
  {
    id: 12,
    name: "canon",
    address: "7th Floor, Tower B,  Building # 5,  DLF Epitome,  DLF Phase III",
    companyLogoUrl: "https://logo.clearbit.com/www.canon.com",
    pincode: "122002",
    phoneNo: "0124 4160000",
    extn: null,
    city: null,
    state: null,
    totalEmployees: 5000,
    companyRevenue: "500",
    country: "India",
    geographyName: "Asia",
    wedsite: "www.canon.co.in",
    symbol: null,
    listingName: null,
    introduction:
      'Canon India Private Limited was incorporated in the year 1997; and is based in Gurgaon, India. It acts as a subsidiary Company of Canon Singapore Pte Ltd. The company is dedicated into the business of Electronics industry. It offers products like Interchangeable Lens Camera, Compact Cameras, Compact Photo Printers, Personal Camcorders, Fax Machines, Single Function Printers, Multifunction Printers, Scanners, Inkjet, Paper, Toner, Digital Copiers, Multifunctional Peripherals, Digital Cameras, Digital Camcorders , Dye Sub Photo Printers and Semiconductors, Card Printers & Cable ID printers Binoculars, etc. Canon has around 100 primary channel partners 14 National Retail Chain partners. It is an ISO 9001, ISO 14001, OHSAS 18001 certified company. The Company was certified for its "Strong commitment to excel" at the CII-EXIM Business Excellence Award. It is headquartered in Japan and has offices located in China, Hong Kong, Singapore,North America, Middle East, Africa, Latin America, Europe and Oceania etc',
    shortIntro: 'Canon India Private Limited was incorporated in the year 1997; and is based in Gurgaon, India. It acts as a subsidiary Company of Canon Singapore Pte Ltd. The company is dedicated into the business of Electronics industry. It offers products like Interchangeable Lens Camera, Compact Cameras, Compact Photo Printers, Personal Camcorders, Fax Machines, Single Function Printers, Multifunction Printers, Scanners, Inkjet, Paper, Toner, Digital Copiers, Multifunctional Peripherals, Digital Cameras, Digital Camcorders , Dye Sub Photo Printers and Semiconductors, Card Printers & Cable ID printers Binoculars, etc. Canon has around 100 primary channel partners 14 National Retail Chain partners. It is an ISO 9001, ISO 14001, OHSAS 18001 certified company. The Company was certified for its "Strong commitment to excel" at the CII-EXIM Business Excellence Award. It is headquartered in Japan and has offices located in China, Hong Kong, Singapore,North America, Middle East, Africa, Latin America, Europe and Oceania etc',
    socialLinks: [],
    industry: null,
    range: { id: 15, name: "1001-2500", description: null },
    revenue: { id: 18, name: "5000 Above", description: null },
    category: null,
  },
  {
    id: 16,
    name: "Dabur India Ltd",
    address: "Kaushambi, Ghaziabad, Uttar Pradesh, India",
    companyLogoUrl: "https://logo.clearbit.com/www.dabur.com",
    pincode: "201010",
    phoneNo: "120 3962100 ",
    extn: null,
    city: "Gaziabad",
    state: "uttar pradesh",
    totalEmployees: 5000,
    companyRevenue: "5000",
    country: "India",
    geographyName: "Asia",
    wedsite: "www.dabur.com",
    symbol: null,
    listingName: null,
    introduction:
      "Dabur India Limited was incorporated in the year 1884 and is based in Ghaziabad, India. It is one of the Indias largest Ayurvedic medicine and natural consumer products manufacturer. Dabur as the master brand for natural healthcare products, Vatika for premium hair care, Hajmola for digestives,",
    shortIntro: "Dabur India Limited was incorporated in the year 1884 and is based in Ghaziabad, India. It is one of the Indias largest Ayurvedic medicine and natural consumer products manufacturer. Dabur as the master brand for natural healthcare products, Vatika for premium hair care, Hajmola for digestives,",
    socialLinks: [],
    industry: { id: 15, name: "Business Supplies", description: null },
    range: null,
    revenue: { id: 17, name: "1001 and 5000", description: null },
    category: null,
  },
  {
    id: 17,
    name: "Paul Wurth India Pvt Ltd",
    address: "Plot N° 286, 2nd Floor, Udyog Vihar, Phase II, Gurugram, Haryana",
    companyLogoUrl: "https://logo.clearbit.com/www.paulwurth.com",
    pincode: "122016",
    phoneNo: "91 124 4523200",
    extn: null,
    city: "Gurgaon",
    state: "Haryana",
    totalEmployees: 200,
    companyRevenue: "500",
    country: "India",
    geographyName: "Asia",
    wedsite: "www.paulwurth.com",
    symbol: null,
    listingName: null,
    introduction:
      "Paul Wurth India Private Limited was incorporated in the year 1993 and acts as a subsidiary of Paul Wurth Group, Europe. The company is dedicated into the business of mechanical & engineering industry. It offers services and products like Iron Making, Stockhouse & Charging, Hot Blast Generation, Blast Furnace Valves, Coke Making, Coke Oven Automation, Steel Making, Non Ferrous Metals, Pyrometallurgy, Electrometallurgy, Civil & Environment Engineering, etc. The company has offices located across globe",
    shortIntro: null,
    socialLinks: [],
    industry: null,
    range: null,
    revenue: { id: 14, name: "101-300", description: null },
    category: null,
  },
  {
    id: 27,
    name: "Dassault Systems India Pvt Ltd",
    address: "12th Floor, Building 10 C, Cyber City Phase 2, Gurugram",
    companyLogoUrl: "https://logo.clearbit.com/www.3ds.com",
    pincode: "122002",
    phoneNo: null,
    extn: null,
    city: "Gurgaon",
    state: "Haryana",
    totalEmployees: null,
    companyRevenue: "500",
    country: "india",
    geographyName: null,
    wedsite: "www.3ds.com",
    symbol: null,
    listingName: null,
    introduction:
      "Dassault Systemes India Private Limited was incorporated in the year 1981.The company is engaged in the business of providing IT Services & Software Applications. The company offers Solidworks 3D design software for 3D and electrical design, simulation, product data management, and technical communication, CATIA, an engineering and design software for product 3D computer-aided design (CAD), GEOVIA, which models and simulates the earth; and BIOVIA that provides a scientific collaborative environment for biological formulated products and advanced materials. It also provides SIMULIA, a simulation software solution for product, nature, and life; DELMIA manufacturing operations management solutions that enable to improve visibility into, control over, and synchronization across manufacturing operations and supply chain processes. The company acts as a subsidiary of Dassault Group, France. The company is based in Gurugram, India & has offices located across the globe",
    shortIntro: null,
    socialLinks: [],
    industry: null,
    range: null,
    revenue: null,
    category: null,
  },
  {
    id: 31,
    name: "Daikin Airconditioning India Pvt Ltd",
    address:
      "12th Floor, Building No. 9, Tower A, DLF Cyber City, DLF Phase - III, Gurugram, Haryana, India, 122002",
    companyLogoUrl: "https://logo.clearbit.com/www.daikinindia.com",
    pincode: "122002",
    phoneNo: null,
    extn: null,
    city: "Gurgaon",
    state: "Haryana",
    totalEmployees: 500,
    companyRevenue: "5000",
    country: "India",
    geographyName: null,
    wedsite: "http://www.daikinindia.com/",
    symbol: null,
    listingName: null,
    introduction: "",
    shortIntro: null,
    socialLinks: [],
    industry: null,
    range: null,
    revenue: null,
    category: null,
  },
];
